name: Statoscope Bundle Analytics

on:
  pull_request:
    branches:
      - '*'

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Cache results
        uses: actions/cache@v3
        id: cache-results
        with:
          path: |
            node_modules
          key: ${{ github.sha }}
  statoscope:
    needs:
      - install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore cache
        uses: actions/cache@v3
        id: restore-cache
        with:
          path: |
            node_modules
          key: ${{ github.sha }}
      - name: Build
        run: npm run build:production; cp public/build-stats.json input.json
      - name: Download reference stats
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: upload-main-stats.yml
          workflow_conclusion: success
          name: main-stats
          path: ./
        continue-on-error: true
      - name: Validate
        run: npm run statoscope:validate-diff
      - name: Query stats
        if: "github.event_name == 'pull_request'"
        run: cat .github/workflows/statoscope-comment.jora | npx --no-install @statoscope/cli query --input input.json --input reference.json > result.json
      - name: Hide bot comments
        uses: int128/hide-comment-action@v1
      - name: Comment PR
        if: "github.event_name == 'pull_request'"
        uses: actions/github-script@v6.0.0
        with:
          script: |
            const createStatoscopeComment = require('./dev/createStatoscopeComment');
            await createStatoscopeComment({ github, context, core })
